name: OEM GSI Builder

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # ... (other steps)

      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ secrets.USERNAME }}" "USERNAME secret"
          required "${{ secrets.PASSWORD }}" "PASSWORD secret"

          # ... (other checks)

      - name: Setup ErfanGSIs Tools
        run: |
          git clone --recurse-submodules "${{ steps.config.outputs.tool_repo }}"
          bash ErfanGSIs/setup.sh
          sed -i '$d' ErfanGSIs/url2GSI.sh

      # ... (other steps)

      - name: Upload
        run: |
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          sshpass -p "${{ secrets.PASSWORD }}" rsync -arsP -e ssh build/ "${{ secrets.USERNAME }}@frs.sourceforge.net:${{ steps.config.outputs.sourceforge_dir }}"

      - name: Telegram Notify
        if: ${{ steps.config.outputs.tg_chat_ids != 0 }}
        run: |
          BOT_TOKEN="${{ secrets.TG_BOT_TOKEN }}"
          CHAT_IDS="${{ steps.config.outputs.tg_chat_ids }}"
          TG_URL="https://api.telegram.org/bot$BOT_TOKEN/sendMessage"

          # ... (other notification logic)

